baseURL = "localhost:1313/"
languageCode = "en-GB"
title = "Jan Schutte"
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe= true

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2

[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML"]